// Coverage report: intersects a font's codepoint set with the curated
// Unicode block data generated by tools/build_data.py.

import data from './data/blocks.json'

export const unicodeVersion = data.unicodeVersion

// Cell states:
//   present — assigned in Unicode, mapped in the font
//   missing — assigned in Unicode, absent from the font
//   extra   — NOT assigned in Unicode (yet), but the font maps it anyway
//             (common for provisional currency signs etc.)
// Unassigned codepoints the font does not cover produce no cell at all.

export function buildReport(codepoints) {
  const groups = data.groups.map((g) => ({
    name: g.name,
    blocks: g.blocks.map((b) => buildBlock(b, codepoints)),
  }))

  const curated = groups.flatMap((g) => g.blocks)
  const totals = {
    assigned: curated.reduce((n, b) => n + b.assignedCount, 0),
    present: curated.reduce((n, b) => n + b.presentCount, 0),
    mapped: codepoints.size,
  }

  return { groups, totals, outside: buildOutside(codepoints, curated) }
}

function buildBlock(block, codepoints) {
  const assigned = new Set()
  for (const [a, b] of block.assigned) {
    for (let cp = a; cp <= b; cp++) assigned.add(cp)
  }

  const cells = []
  const missing = []
  let presentCount = 0
  let extraCount = 0
  let idx = 0
  for (let cp = block.start; cp <= block.end; cp++) {
    if (assigned.has(cp)) {
      const name = block.names[idx]
      const cat = block.cats[idx]
      idx++
      if (codepoints.has(cp)) {
        presentCount++
        cells.push({ cp, name, cat, state: 'present' })
      } else {
        missing.push({ cp, name })
        cells.push({ cp, name, cat, state: 'missing' })
      }
    } else if (codepoints.has(cp)) {
      extraCount++
      cells.push({ cp, name: null, cat: null, state: 'extra' })
    }
  }

  return {
    name: block.name,
    start: block.start,
    end: block.end,
    assignedCount: block.assignedCount,
    presentCount,
    extraCount,
    missing,
    cells,
  }
}

// Codepoints mapped by the font that fall outside every curated block,
// summarized per Unicode block name.
function buildOutside(codepoints, curated) {
  const counts = new Map()
  for (const cp of codepoints) {
    if (curated.some((b) => cp >= b.start && cp <= b.end)) continue
    const name = findBlockName(cp)
    counts.set(name, (counts.get(name) || 0) + 1)
  }
  return [...counts.entries()]
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count)
}

function findBlockName(cp) {
  const blocks = data.allBlocks // sorted [[start, end, name], ...]
  let lo = 0
  let hi = blocks.length - 1
  while (lo <= hi) {
    const mid = (lo + hi) >> 1
    const [start, end, name] = blocks[mid]
    if (cp < start) hi = mid - 1
    else if (cp > end) lo = mid + 1
    else return name
  }
  return 'Unassigned'
}
