// Coverage report: intersects a font's codepoint set with the curated
// Unicode block data generated by tools/build_data.py.

import data from './data/blocks.json'

export const unicodeVersion = data.unicodeVersion

// Cell states:
//   present — assigned in Unicode, mapped in the font
//   missing — assigned in Unicode, absent from the font
//   extra   — NOT assigned in Unicode (yet), but the font maps it anyway
//             (common for provisional currency signs etc.)
// Unassigned codepoints the font does not cover produce no cell at all.

export function buildReport(font) {
  const codepoints = font.codepoints
  const groups = data.groups.map((g) => ({
    name: g.name,
    blocks: g.blocks.map((b) => buildBlock(b, codepoints)),
  }))

  const curated = groups.flatMap((g) => g.blocks)
  const totals = {
    assigned: curated.reduce((n, b) => n + b.assignedCount, 0),
    present: curated.reduce((n, b) => n + b.presentCount, 0),
    mapped: codepoints.size,
  }

  return {
    groups,
    totals,
    outside: buildOutside(codepoints, curated),
    glyphs: buildGlyphs(font),
  }
}

function buildBlock(block, codepoints) {
  const assigned = new Set()
  for (const [a, b] of block.assigned) {
    for (let cp = a; cp <= b; cp++) assigned.add(cp)
  }

  const cells = []
  const missing = []
  let presentCount = 0
  let extraCount = 0
  let idx = 0
  for (let cp = block.start; cp <= block.end; cp++) {
    if (assigned.has(cp)) {
      const name = block.names[idx]
      const cat = block.cats[idx]
      idx++
      if (codepoints.has(cp)) {
        presentCount++
        cells.push({ cp, name, cat, state: 'present' })
      } else {
        missing.push({ cp, name })
        cells.push({ cp, name, cat, state: 'missing' })
      }
    } else if (codepoints.has(cp)) {
      extraCount++
      cells.push({ cp, name: null, cat: null, state: 'extra' })
    }
  }

  return {
    name: block.name,
    start: block.start,
    end: block.end,
    assignedCount: block.assignedCount,
    presentCount,
    extraCount,
    missing,
    cells,
  }
}

// ---------------------------------------------------- elsewhere in the font

// Mapped codepoints the curated blocks above do not already show, grouped by
// their real Unicode block. Unlike the coverage report this lists only what
// is there: it is the rest of the font's contents, not a checklist.
function buildOutside(codepoints, curated) {
  const byBlock = new Map()
  for (const cp of [...codepoints].sort((a, b) => a - b)) {
    if (curated.some((b) => cp >= b.start && cp <= b.end)) continue
    const block = findBlock(cp)
    const key = block ? block[0] : -1
    let entry = byBlock.get(key)
    if (!entry) {
      entry = {
        name: block ? block[2] : 'Outside any block',
        start: block ? block[0] : cp,
        end: block ? block[1] : cp,
        cps: [],
        assignedCount: 0,
        extraCount: 0,
      }
      byBlock.set(key, entry)
    }
    entry.cps.push(cp)
    if (!block) entry.end = cp
    if (categoryOf(cp)) entry.assignedCount++
    else entry.extraCount++
  }

  const blocks = [...byBlock.values()].sort((a, b) => a.start - b.start)
  return { blocks, count: blocks.reduce((n, b) => n + b.cps.length, 0) }
}

// Glyphs no codepoint reaches: alternates, ligature targets, mark components.
// They are real glyphs in the font, just not addressable as characters.
function buildGlyphs({ numGlyphs, encodedGids, glyphNames, zeroWidthGids }) {
  if (!numGlyphs) return { numGlyphs: null, encoded: 0, unencoded: [] }
  const unencoded = []
  for (let gid = 0; gid < numGlyphs; gid++) {
    if (encodedGids.has(gid)) continue
    unencoded.push({
      gid,
      name: glyphNames?.[gid] ?? null,
      mark: zeroWidthGids?.has(gid) ?? false,
    })
  }
  return { numGlyphs, encoded: encodedGids.size, unencoded, named: !!glyphNames }
}

// General category of an assigned codepoint, or null when Unicode has not
// assigned it. Run-length data, so a binary search over the runs.
export function categoryOf(cp) {
  const runs = data.catRuns // sorted [[start, end, catIndex], ...]
  let lo = 0
  let hi = runs.length - 1
  while (lo <= hi) {
    const mid = (lo + hi) >> 1
    const [start, end, cat] = runs[mid]
    if (cp < start) hi = mid - 1
    else if (cp > end) lo = mid + 1
    else return data.catNames[cat]
  }
  return null
}

function findBlock(cp) {
  const blocks = data.allBlocks // sorted [[start, end, name], ...]
  let lo = 0
  let hi = blocks.length - 1
  while (lo <= hi) {
    const mid = (lo + hi) >> 1
    const block = blocks[mid]
    if (cp < block[0]) hi = mid - 1
    else if (cp > block[1]) lo = mid + 1
    else return block
  }
  return null
}
